# This make the database persistent.
volumes:
  demo-postgres-data:
    driver: local
  demo-pgadmin-data:
    driver: local

services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    env_file:
      - .env
    container_name: database
    volumes:
      - "demo-postgres-data:/var/lib/postgresql/data"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    restart: 'always'
    ports:
      - "${DB_EXPOSED_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    image: 'dpage/pgadmin4:${PGADMIN_VERSION}'
    env_file:
      - .env
    container_name: pgadmin-tool
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
    volumes:
      - "./storage/pgadmin_pgadmin.com:/var/lib/pgadmin/storage/pgadmin_pgadmin.com"
      - "demo-pgadmin-data:/var/lib/pgadmin"
    depends_on:
      - postgres